In [2]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int32


In [3]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)


True


In [4]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [5]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1, 2, 3, 4])
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1. 2. 3. 4.]


In [6]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.123456789, 2.987654321], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1.1234568 2.9876542]


In [7]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

# Example usage
arr = np.array([1, 2, 3, 4])
print(array_attributes(arr))


((4,), 4, dtype('int32'))


In [8]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim

# Example usage
arr = np.array([[1, 2], [3, 4]])
print(array_dimension(arr))


2


In [9]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

# Example usage
arr = np.array([1, 2, 3, 4], dtype=np.int32)
print(item_size_info(arr))


(4, 16)


In [10]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))


((2, 2), (8, 4))


In [11]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)

# Example usage
print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


In [12]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage
print(generate_range_array(0, 10, 2))


[0 2 4 6 8]


In [14]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
print(generate_linear_space(0, 1, 5))


[0.   0.25 0.5  0.75 1.  ]


In [15]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

# Example usage
print(create_identity_matrix(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(lst):
    return np.array(lst)

# Example usage
print(list_to_array([1, 2, 3, 4]))


[1 2 3 4]


In [17]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
print("Original Array:", arr)
print("View Array:", view_arr)


Original Array: [1 2 3 4]
View Array: [1 2 3 4]


In [18]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print(concatenate_arrays(arr1, arr2, axis=0))


[[1 2]
 [3 4]
 [5 6]]


In [19]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print(np.concatenate((arr1, arr2.T), axis=1))  # Transposing arr2 to match the shape


[[1 2 5]
 [3 4 6]]


In [20]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays):
    return np.vstack(arrays)

# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(vertical_stack([arr1, arr2]))


[[1 2 3]
 [4 5 6]]


In [21]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

# Example usage
print(range_array(1, 10, 2))


[1 3 5 7 9]


In [22]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def equally_spaced_values(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
print(equally_spaced_values(0, 1, 10))


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def log_space_values(start, stop, num):
    return np.logspace(np.log10(start), np.log10(stop), num)

# Example usage
print(log_space_values(1, 1000, 5))


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd

np_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(np_array, columns=['A', 'B', 'C'])
print(df)


    A   B   C
0  34   1  63
1  31  66  16
2   5  13  59
3  13  27  83
4  69  27  40


In [25]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd

np_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(np_array, columns=['A', 'B', 'C'])
print(df)


    A   B   C
0  38  88  99
1  44  12  52
2  60  47   3
3  15  90  38
4  86  84  17


In [26]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negative_values(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
df = pd.DataFrame({'A': [1, -2, 3], 'B': [-4, 5, -6]})
print(replace_negative_values(df, 'A'))


   A  B
0  1 -4
1  0  5
2  3 -6


In [27]:
# 26. Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40, 50])
element = arr[2]
print(element)


30


In [35]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print(element)

6


In [36]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
elements = arr[arr > 5]
print(elements)

[ 8 10  7]


In [37]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
slice_elements = arr[2:6]
print(slice_elements)


[3 4 5 6]


In [38]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [28]:
# 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements_by_indices(array, indices):
    return array[indices]

# Example usage
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
indices = [0, 2]  # Extract rows 0 and 2
print(extract_elements_by_indices(array, indices))


[[10 20 30]
 [70 80 90]]


In [29]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

# Example usage
arr = np.array([1, 5, 8, 12])
threshold = 6
print(filter_greater_than_threshold(arr, threshold))


[ 8 12]


In [30]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements_3d(array, dim1_indices, dim2_indices, dim3_indices):
    return array[dim1_indices, dim2_indices, dim3_indices]

# Example usage
array = np.random.randint(1, 10, size=(4, 4, 4))
dim1_indices = [0, 1]
dim2_indices = [1, 2]
dim3_indices = [2, 3]
print(extract_elements_3d(array, dim1_indices, dim2_indices, dim3_indices))


[3 8]


In [31]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[condition1 & condition2]

# Example usage
arr = np.array([1, 2, 3, 4, 5, 6])
condition1 = arr > 2
condition2 = arr < 5
print(elements_satisfying_conditions(arr, condition1, condition2))


[3 4]


In [32]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements_from_2d(array, row_indices, col_indices):
    return array[row_indices, col_indices]

# Example usage
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = [0, 1]
col_indices = [2, 0]
print(extract_elements_from_2d(array, row_indices, col_indices))


[30 40]


In [33]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr + 5
print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [70]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

# Broadcasting arr1 to match the shape of arr2 for element-wise multiplication
result = arr1 * arr2[:, :3]  # Make sure arr2 has the same number of columns as arr1

print(result)


[[ 4 10 18]
 [ 8 18 30]
 [12 26 42]]


In [71]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])

# Reshape arr1 to be compatible for broadcasting
arr1_reshaped = arr1[:, :3]  # Adjust to match the number of columns in arr2

# Adding arr1_reshaped to each row of arr2
result = arr2 + arr1_reshaped

print(result)


[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [ ]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [69]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

# Adjusting shapes for broadcasting
arr2_expanded = np.expand_dims(arr2, axis=2)  # Shape (2, 2, 1)
arr2_broadcasted = np.broadcast_to(arr2_expanded, (2, 3, 2))  # Shape (2, 3, 2)

result = arr1[:, :, np.newaxis] * arr2_broadcasted
print(result)


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2,1)  and requested shape (2,3,2)

In [42]:
# 41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_wise_mean = arr.mean(axis=0)
print(column_wise_mean)

[2.5 3.5 4.5]


In [43]:
# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = arr.max(axis=1)
print(row_max)


[3 6]


In [44]:
# 43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
indices_of_max = arr.argmax(axis=0)
print(indices_of_max)


[1 1 1]


In [67]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(array, window_size):
   
    return np.array([np.convolve(row, np.ones(window_size), mode='valid') for row in array])

moving_sum_result = moving_sum(arr, window_size=2)
print(moving_sum_result)


[[ 3.  5.]
 [ 9. 11.]]


In [46]:
# 45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even = np.all(arr % 2 == 0, axis=0)
print(all_even)

[False False False]


In [47]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3
reshaped_matrix = original_array.reshape(m, n)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [48]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_matrix(matrix):
    return matrix.flatten()

flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [49]:
# 48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

concatenated_array = concatenate_arrays(array1, array2)
print(concatenated_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [66]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(array, indices_or_sections, axis=0):
    return np.split(array, indices_or_sections, axis=axis)

split_arrays = split_array(original_array, 3) 
print(split_arrays)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [51]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_and_delete(array, insert_indices, insert_values, delete_indices):
    array = np.insert(array, insert_indices, insert_values)
    array = np.delete(array, delete_indices)
    return array

result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)

[ 1 10  4 11  5]


In [ ]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1, 10, size=(3, 3))
arr2 = np.arange(1, 10).reshape(3, 3)  # Reshape to match the dimensions of arr1
result_addition = arr1 + arr2
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Element-wise addition:\n", result_addition)


arr1:
 [[9 4 6]
 [9 2 4]
 [6 8 5]]
arr2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element-wise addition:
 [[10  6  9]
 [13  7 10]
 [13 16 14]]


In [ ]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10.
# Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result_subtraction = arr1 - arr2
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Element-wise subtraction:\n", result_subtraction)


arr1:
 [10  9  8  7  6  5  4  3  2  1]
arr2:
 [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction:
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [65]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 3.
# Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1, 10, size=(3, 3))
arr2 = np.arange(1, 4).reshape(3, 1)  
arr2 = np.broadcast_to(arr2, arr1.shape)  
result_multiplication = arr1 * arr2
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Element-wise multiplication:\n", result_multiplication)


arr1:
 [[2 2 8]
 [2 3 7]
 [7 3 3]]
arr2:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Element-wise multiplication:
 [[ 2  2  8]
 [ 4  6 14]
 [21  9  9]]


In [ ]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5.
# Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result_division = arr1 / arr2
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Element-wise division:\n", result_division)


arr1:
 [ 2  4  6  8 10]
arr2:
 [1 2 3 4 5]
Element-wise division:
 [2. 2. 2. 2. 2.]


In [ ]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed.
# Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0, -1)
result_exponentiation = np.power(arr1, arr2)
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Exponentiation (arr1^arr2):\n", result_exponentiation)


arr1:
 [1 2 3 4 5]
arr2:
 [5 4 3 2 1]
Exponentiation (arr1^arr2):
 [ 1 16 27 16  5]


In [52]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(array, substring):
    return np.sum(np.char.find(array, substring) != -1)

count_hello = count_substring(arr, 'hello')
print(count_hello)


3


In [53]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(array):
    return np.char.replace(array, np.char.lower(array), '')

uppercase_chars = extract_uppercase(arr)
print(uppercase_chars)

['Hello' 'World' 'OpenAI' 'GPT']


In [54]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(array, old_substring, new_substring):
    return np.char.replace(array, old_substring, new_substring)

replaced_array = replace_substring(arr, 'apple', 'orange')
print(replaced_array)

['orange' 'banana' 'grape' 'pineorange']


In [55]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_elementwise(array1, array2):
    return np.char.add(array1, array2)

concatenated_array = concatenate_elementwise(arr1, arr2)
print(concatenated_array)

['HelloOpen' 'WorldAI']


In [56]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(array):
    return np.max(np.char.str_len(array))

max_length = longest_string_length(arr)
print(max_length)

9


In [ ]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print("Dataset:\n", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Dataset:
 [ 86 145 394  97 966 445 270   3 321 619 624 136  91 110  69 108 880 532
 960 622 450 850 297 264 625  10 897 403 282 375  55 887 623 526 606 511
 928 258 713  14 951 925 843 401 793  34 891 127 377 512 900  29 347 552
 614 621 219   7 817 860 299 160 304  81 472 386 517 882 105 219  87 216
 312 373 373 962 501 944 779 474 355 730 973 847 355 692 223 299 723 818
 625 373 492 887 956 268 626 547 238 963]
Mean: 483.08
Median: 461.0
Variance: 89640.9736
Standard Deviation: 299.4010247143453


In [ ]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

data = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("Data:\n", data)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Data:
 [ 74  74  84  73  50  29  93  26  80  24  23  64  48  42  14  76  57   2
  56   5  28  60  74  69  71  94   2  83  65  98  48  86  16  65  66  52
  69  60  20  90  95  83  91 100  31  93  78  51  42  83]
25th Percentile: 42.0
75th Percentile: 82.25


In [ ]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

array1 = np.random.rand(10)
array2 = np.random.rand(10)
correlation_matrix = np.corrcoef(array1, array2)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Correlation Coefficient Matrix:\n", correlation_matrix)


Array 1:
 [0.34236967 0.83189568 0.30750573 0.86687532 0.91504096 0.90276856
 0.89340786 0.37700372 0.71271    0.40513538]
Array 2:
 [0.60944534 0.50755377 0.18487461 0.25982475 0.64497151 0.22499994
 0.16418184 0.86304725 0.58918627 0.98666556]
Correlation Coefficient Matrix:
 [[ 1.         -0.44039562]
 [-0.44039562  1.        ]]


In [ ]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_matrix_multiplication = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Multiplication Result:\n", result_matrix_multiplication)


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [ ]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

array = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)  # Median
percentile_90 = np.percentile(array, 90)
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print("Array:\n", array)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile:", first_quartile)
print("Third Quartile:", third_quartile)


Array:
 [912 250 966 689 352 543 700 369 779  10 155 216 410 545 186 427 265 772
 904 665 113 310 131 130  35 437 867 762 952 807 126 393  78 744 750 359
  34 580 546 236 517 453 820 941  33 664 518 799 307 294]
10th Percentile: 109.50000000000001
50th Percentile (Median): 445.0
90th Percentile: 870.7
First Quartile: 239.5
Third Quartile: 748.5


In [ ]:
# 66. Create a NumPy array of integers and find the index of a specific element.

array = np.array([10, 20, 30, 40, 50])
element = 30
index = np.where(array == element)[0][0]  # Get the index of the element

print("Array:\n", array)
print("Element:", element)
print("Index of Element:", index)


Array:
 [10 20 30 40 50]
Element: 30
Index of Element: 2


In [ ]:
# 67. Generate a random NumPy array and sort it in ascending order.

array = np.random.randint(1, 100, size=20)
sorted_array = np.sort(array)

print("Original Array:\n", array)
print("Sorted Array:\n", sorted_array)


Original Array:
 [14 39  7 22 68 28 41  3 44  3 32 56 76 16 54 85 38 82 15 79]
Sorted Array:
 [ 3  3  7 14 15 16 22 28 32 38 39 41 44 54 56 68 76 79 82 85]


In [57]:
# 68. Filter elements >20 in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_elements = arr[arr > 20]
print(filtered_elements)

[25 42 30]


In [58]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
divisible_by_3 = arr[arr % 3 == 0]
print(divisible_by_3)

[12 15]


In [59]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filtered_elements = arr[(arr >= 20) & (arr <= 40)]
print(filtered_elements)


[20 30 40]


In [60]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)


=


In [61]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)


[16777216 33554432 50331648]


In [62]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder()
print(new_arr)


[16777216 33554432 50331648]


In [63]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder('>' if arr.dtype.byteorder == '<' else '<')
print(new_arr)

[1 2 3]


In [64]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
is_swapping_needed = arr.dtype.byteorder not in ('=', '|')
print(is_swapping_needed)

False


In [ ]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100

print("Original arr1:\n", arr1)
print("Modified copy_arr:\n", copy_arr)
# `arr1` should remain unchanged


Original arr1:
 [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr:
 [100   2   3   4   5   6   7   8   9  10]


In [ ]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100

print("Original matrix:\n", matrix)
print("Modified view_slice:\n", view_slice)
# `matrix` should reflect the change in `view_slice`


Original matrix:
 [[100   6   4]
 [  3   7   5]
 [  4   6   9]]
Modified view_slice:
 [[100   6]
 [  3   7]]


In [ ]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape((4, 3))
view_b = array_a[1:3, 1:3]
view_b += 5

print("Original array_a:\n", array_a)
print("Modified view_b:\n", view_b)
# `array_a` should reflect the change in `view_b`


Original array_a:
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]
Modified view_b:
 [[10 11]
 [13 14]]


In [ ]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape((2, 4))
reshaped_view = orig_array.reshape((4, 2))
reshaped_view[0, 0] = 100

print("Original orig_array:\n", orig_array)
print("Modified reshaped_view:\n", reshaped_view)
# `orig_array` should reflect the change in `reshaped_view`


Original orig_array:
 [[100   2   3   4]
 [  5   6   7   8]]
Modified reshaped_view:
 [[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [ ]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100

print("Original data:\n", data)
print("Modified data_copy:\n", data_copy)
# `data` should remain unchanged


Original data:
 [[7 8 6 4]
 [5 6 2 3]
 [5 3 9 9]]
Modified data_copy:
 [100   8   6   6   9   9]


In [ ]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
addition_result = A + B
subtraction_result = A - B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition Result:\n", addition_result)
print("Subtraction Result:\n", subtraction_result)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition Result:
 [[ 6  8]
 [10 12]]
Subtraction Result:
 [[-4 -4]
 [-4 -4]]


In [ ]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))
multiplication_result = np.dot(C, D)

print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix Multiplication Result:\n", multiplication_result)


Matrix C:
 [[9 9]
 [7 2]
 [7 6]]
Matrix D:
 [[1 7 7 2]
 [4 9 6 6]]
Matrix Multiplication Result:
 [[ 45 144 117  72]
 [ 15  67  61  26]
 [ 31 103  85  50]]


In [ ]:
# 83. Create a matrix `E` and find its transpose.

E = np.random.randint(1, 10, size=(3, 4))
transpose_E = np.transpose(E)

print("Matrix E:\n", E)
print("Transpose of Matrix E:\n", transpose_E)


Matrix E:
 [[6 9 4 8]
 [7 3 9 4]
 [4 8 6 6]]
Transpose of Matrix E:
 [[6 7 4]
 [9 3 8]
 [4 9 6]
 [8 4 6]]


In [ ]:
# 85. Create a square matrix `G` and find its inverse.

G = np.array([[1, 2], [3, 4]])
inverse_G = np.linalg.inv(G)

print("Matrix G:\n", G)
print("Inverse of Matrix G:\n", inverse_G)


Matrix G:
 [[1 2]
 [3 4]]
Inverse of Matrix G:
 [[-2.   1. ]
 [ 1.5 -0.5]]
